# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CmpntProcessingTime(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_time: datetime=None, end_time: datetime=None, duration_in_s: float=None):  # noqa: E501
        """CmpntProcessingTime - a model defined in Swagger

        :param start_time: The start_time of this CmpntProcessingTime.  # noqa: E501
        :type start_time: datetime
        :param end_time: The end_time of this CmpntProcessingTime.  # noqa: E501
        :type end_time: datetime
        :param duration_in_s: The duration_in_s of this CmpntProcessingTime.  # noqa: E501
        :type duration_in_s: float
        """
        self.swagger_types = {
            'start_time': datetime,
            'end_time': datetime,
            'duration_in_s': float
        }

        self.attribute_map = {
            'start_time': 'start_time',
            'end_time': 'end_time',
            'duration_in_s': 'duration_in_s'
        }
        self._start_time = start_time
        self._end_time = end_time
        self._duration_in_s = duration_in_s

    @classmethod
    def from_dict(cls, dikt) -> 'CmpntProcessingTime':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cmpnt_processing_time of this CmpntProcessingTime.  # noqa: E501
        :rtype: CmpntProcessingTime
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this CmpntProcessingTime.


        :return: The start_time of this CmpntProcessingTime.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this CmpntProcessingTime.


        :param start_time: The start_time of this CmpntProcessingTime.
        :type start_time: datetime
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self) -> datetime:
        """Gets the end_time of this CmpntProcessingTime.


        :return: The end_time of this CmpntProcessingTime.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: datetime):
        """Sets the end_time of this CmpntProcessingTime.


        :param end_time: The end_time of this CmpntProcessingTime.
        :type end_time: datetime
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def duration_in_s(self) -> float:
        """Gets the duration_in_s of this CmpntProcessingTime.


        :return: The duration_in_s of this CmpntProcessingTime.
        :rtype: float
        """
        return self._duration_in_s

    @duration_in_s.setter
    def duration_in_s(self, duration_in_s: float):
        """Sets the duration_in_s of this CmpntProcessingTime.


        :param duration_in_s: The duration_in_s of this CmpntProcessingTime.
        :type duration_in_s: float
        """
        if duration_in_s is None:
            raise ValueError("Invalid value for `duration_in_s`, must not be `None`")  # noqa: E501

        self._duration_in_s = duration_in_s
