# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cmpnt_processing_time import CmpntProcessingTime  # noqa: F401,E501
from swagger_server import util


class Model200Response(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reference_id: str=None, uid: str=None, status_code: int=None, processing_time: CmpntProcessingTime=None, result: str=None, confidence: float=None):  # noqa: E501
        """Model200Response - a model defined in Swagger

        :param reference_id: The reference_id of this Model200Response.  # noqa: E501
        :type reference_id: str
        :param uid: The uid of this Model200Response.  # noqa: E501
        :type uid: str
        :param status_code: The status_code of this Model200Response.  # noqa: E501
        :type status_code: int
        :param processing_time: The processing_time of this Model200Response.  # noqa: E501
        :type processing_time: CmpntProcessingTime
        :param result: The result of this Model200Response.  # noqa: E501
        :type result: str
        :param confidence: The confidence of this Model200Response.  # noqa: E501
        :type confidence: float
        """
        self.swagger_types = {
            'reference_id': str,
            'uid': str,
            'status_code': int,
            'processing_time': CmpntProcessingTime,
            'result': str,
            'confidence': float
        }

        self.attribute_map = {
            'reference_id': 'reference_id',
            'uid': 'uid',
            'status_code': 'status_code',
            'processing_time': 'processing_time',
            'result': 'result',
            'confidence': 'confidence'
        }
        self._reference_id = reference_id
        self._uid = uid
        self._status_code = status_code
        self._processing_time = processing_time
        self._result = result
        self._confidence = confidence

    @classmethod
    def from_dict(cls, dikt) -> 'Model200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 200_response of this Model200Response.  # noqa: E501
        :rtype: Model200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reference_id(self) -> str:
        """Gets the reference_id of this Model200Response.


        :return: The reference_id of this Model200Response.
        :rtype: str
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id: str):
        """Sets the reference_id of this Model200Response.


        :param reference_id: The reference_id of this Model200Response.
        :type reference_id: str
        """

        self._reference_id = reference_id

    @property
    def uid(self) -> str:
        """Gets the uid of this Model200Response.


        :return: The uid of this Model200Response.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this Model200Response.


        :param uid: The uid of this Model200Response.
        :type uid: str
        """

        self._uid = uid

    @property
    def status_code(self) -> int:
        """Gets the status_code of this Model200Response.


        :return: The status_code of this Model200Response.
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code: int):
        """Sets the status_code of this Model200Response.


        :param status_code: The status_code of this Model200Response.
        :type status_code: int
        """

        self._status_code = status_code

    @property
    def processing_time(self) -> CmpntProcessingTime:
        """Gets the processing_time of this Model200Response.


        :return: The processing_time of this Model200Response.
        :rtype: CmpntProcessingTime
        """
        return self._processing_time

    @processing_time.setter
    def processing_time(self, processing_time: CmpntProcessingTime):
        """Sets the processing_time of this Model200Response.


        :param processing_time: The processing_time of this Model200Response.
        :type processing_time: CmpntProcessingTime
        """

        self._processing_time = processing_time

    @property
    def result(self) -> str:
        """Gets the result of this Model200Response.


        :return: The result of this Model200Response.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this Model200Response.


        :param result: The result of this Model200Response.
        :type result: str
        """

        self._result = result

    @property
    def confidence(self) -> float:
        """Gets the confidence of this Model200Response.


        :return: The confidence of this Model200Response.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence: float):
        """Sets the confidence of this Model200Response.


        :param confidence: The confidence of this Model200Response.
        :type confidence: float
        """

        self._confidence = confidence
